### ISSUE TITLE
Add Github as Remote For Existing Repositories

### ISSUE THREAD

**Issue by hediet** [SrBrahma/GitHub-Repository-Manager#2]
Hey there ;)

I really like your extension!

It would be very cool though if, instead of only offering to clone a newly created repo on github, it would also offer to set the newly created repo as a remote for the already opened git repository.

**Comment by SrBrahma** [comment]
I really appreciate that you liked it :)

So, tell me if I got it right:

You already have a git repository (but not a GitHub repo or not even a repo yet) and want to create a GitHub repo and add this new GitHub repo as a remote to it, with a button next to the "Clone" button when it finishes creating it"?

After some thinking, I now see it as a great idea, as sometimes we are already doing a local project or something else and just want to quickly upload it to GitHub. Nice one!

Do you have another idea than this button next to the "Clone" when the creation is complete? What if the user created the repo but closed the creation success message windows and now "regrets it" (lol)? Maybe a right-click option on the "Not Cloned" repository on the list with a an option like "Add repository as remote"?

And for both, if there are more than one main directories in the workspace, a list to select the directory?

Hmmm...

**Comment by hediet** [comment]
I like your thinking. I think you should have both a button for each list in the tree view and a button in the message.

**Comment by SrBrahma** [comment]
Hey, @hediet! I am sorry for taking so long. My queue of programming projects went a little out of control. I also tried a solution for your issue back then, but I was trying something more complex and my git knowledge was worse than today, that still pretty bad (I created this extension because I hate git and cli programs! And back then, you remember, VSCode haven't any GitHub integration)

In this mean time, VSCode team added its "Publish to GitHub" functionality. While it works, I don't really love it and I still wanted a more integrated solution for my extension, with a more "Look and Feel". Also, this +1yo issue was really bugging me! I wouldn't give up after so long.

I came to this solution, a little different from what we thought, but I think it's better this way: 
![image](https://user-images.githubusercontent.com/28177550/127957974-9ddec86c-8e2c-4bdb-a931-4b31e958dd72.png)

[Explained in README](https://github.com/SrBrahma/GitHub-Repository-Manager/tree/master#-creating-a-repository-for-current-project-)

This way, being another button instead of using the extension "Create Repository" button, the user know, before going through the repository creation process, that his project will be automatically pushed to the new repository.

I haven't added the "Add as Remote" in the context menu. I personally don't think it's needed, I haven't manually added a remote to a GitHub repo for so long, but if I end up thinking it would be a good addition, I can just use some steps I used in this new functionality. If you or anyone else want it, just tell me!

Also, eventually I will add to both repository creation flows, the https://github.com/SrBrahma/GitHub-Repository-Manager/issues/23 integration.

Feel free to report any bug, readme typo or confusing text and new ideas!

🥳
