### ISSUE TITLE
Instead of 'git.defaultClone not set ...' message, change it to a button to set it interactively 

### ISSUE THREAD

**Issue by SrBrahma** [SrBrahma/GitHub-Repository-Manager#29]
Also, could change this setting. There could be a specific setting for the cloned repos path, and if undefined, it would use git.defaultClone... for backward compability.

I have no idea on why I used this git.defaultClone back then. Maybe the Command Pallet > Clone would use this default?

**Comment by zardoy** [comment]
Hey! It would be cool to just add a button, with something like [this](https://github.com/zardoy/github-manager/blob/main/src/core/git.ts#L33). It was also interesting to me to see how these 2 extensions provide the same functionality but via different APIs (views and quickpicks). I wish I knew about your ext before, but feel free to pick ideas/impl from it!

> There could be a specific setting for the cloned repos path

I just wonder why? I mean why don't just use `git.defaultCloneDirectory` as cross-ext setting?

btw you can remove `Visualize without cloning` as GistPad tried to do that and there is GitHub Repositories for that now!

**Comment by SrBrahma** [comment]
Hi!

It's really nice to see someone here! 😄

Yeah, I should improve that when I have the time. I really like this extension of mine and use it everyday, I strange a little that it isn't as popular as I expect and would like. I got really happy and surprised when it reached 10, 100, and now reaching 15k downloads, but I think it's so essential and useful for VsCode... how can people use VS without this? 😆😅

This would help, as it isn't the first time someone mention it (even already received an email about it) and surely it's something that makes a significant amount of new users lose their interest on the ext and certainly just uninstall it as they couldn't get it working at first. Once I used it in a new PC that hadn't yet the ext setup done and it's indeed an ugly issue.

I can't tell you when I will have the time for it as I am busy with stuff with higher priority but not as cool as this hehe but surely will when I can.

Tomorrow I will take a better look in your ext and take a quick peak at its code. Looks nice! Really interesting to see other people who travelled similar paths! Surely we both had one or two identical issues somewhere!

**Comment by SrBrahma** [comment]
Also, I have no memories about the git.defaultCloneDir and why it turned out to be as it's now. Does it have a default value? Maybe I didn't like its default path. Maybe I intended to have a custom path setting so the user could use different paths for specific reasons. Maybe I just used it so I wouldn't need to create another setting. 🤷‍♂️

**Comment by zardoy** [comment]
> It's really nice to see someone here!

Thank you, but I created ext with the intention to provide a way to clone repos as fast as possible, without having to select directory everytime (as I remember WebStorm had something like this in start popup). Also that's why I added depth=1 suggestion. I just binded it to some key and use it whenever need to open some project. I also don't understand how can people use VSCode without something like this. So, feel free to pick the clone implentation, the only thing that I didn't add is cloning progress (but official GitHub Repositories ext has it).

Your extension is good enough, but I think it'd be cool to have clipboard detection for something like this:
- `gh repo clone owner/repo`
- `https://github.com/owner/repo.git`
User can just copy this from GitHub UI and ext can display suggestion to clone desired repo. Here is [example impl](https://github.com/zardoy/npm-the-fastest/blob/eed6cc1119c4f1ac7481543917f26dd02d95eec9/src/core/clipboardDetection.ts#L8).

Or you can go to the end and even add a browser extension to add open in desktop vscode button to every GitHub repo (something similar to [gitpod ext](https://github.com/gitpod-io/browser-extension)).

I think this can give the best GitHub integration with VSCode ever. Of course I wish I had more time to investigate this, though I've never had focus on this.


> Does it have a default value?

It comes with default value setted to `null`. Git internally [uses homedir](https://github.com/microsoft/vscode/blob/745ef8b8264e12b2a704f6b2b60a2ce2cabfcda3/extensions/git/src/commands.ts#L415) otherwise.

**Comment by SrBrahma** [comment]
https://github.com/SrBrahma/GitHub-Repository-Manager/issues/40#issuecomment-1142415695
