### ISSUE TITLE
'git remote show <remoteUrl>' hasn't returned a HEAD branch!

### ISSUE THREAD

**Issue by YuuJinS** [SrBrahma/GitHub-Repository-Manager#35]

**Comment by SrBrahma** [comment]
Hi @YuuJinS !

Thanks for the report. I will fix it asap.

Related: #33

**Comment by SrBrahma** [comment]
Hi!

I've just released 1.3.3 to try to fix it. Seems that Japanese uses a different colon char, '：' instead of the usual ':' (https://en.wikipedia.org/wiki/Japanese_punctuation#Colon), and your git, as your image shows, uses that colon. I've added it to the Regex that gets the Remote HEAD.

Also, if you noticed in your error message, your image only hides one token of the link (the stuff before \@github). I've also fixed this. I will remove your image as it contains non-hidden tokens as it must not be shared.

Please, give it a try and see if it's now working!
